drop table user if exists
create table user (
id bigint generated by default as identity (start with 1),
nick_name varchar(255),
password varchar(255) not null, phone_number varchar(255),
user_name varchar(255) not null,
primary key (id));
drop table authorities if exists
create table authorities (
username varchar(256),
authority varchar(256));